loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1

# loki: 
#   singleBinary: 
#     replicas: 1
#   auth_enabled: false
#   storage:
#     type: s3
#     s3:
#       s3: s3://test:test@localstack.operations.svc.cluster.local:4566/loki-data
#       s3forcepathstyle: true
gateway:
  ingress: 
    enabled: true
    hosts:
      - host: loki.{{.Domain}}
        paths:
          - path: /
            pathType: Prefix