nodeSelector: 
  type: server
metrics:
  service:
    enabled: true
    labels: {}
    annotations: {}
  prometheus:
    # When set to true, it won't check if Prometheus Operator CRDs are deployed
    disableAPICheck: false
    serviceMonitor:
      metricRelabelings: 
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings: 
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
      # (Optional)
      # scrapeTimeout: 5s
      # honorTimestamps: true
      # enableHttp2: true
      # followRedirects: true
      # additionalLabels:
      #   foo: bar
      # namespace: "another-namespace"
      # namespaceSelector: {}
    prometheusRule:
      additionalLabels: {}
      # namespace: "another-namespace"
      rules:
        - alert: TraefikDown
          expr: up{job="traefik"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: {{`"{{ $labels.pod }} on {{ $labels.nodename }} is down"`}}