name: tagger

on:
  push:
    branches:
      - main
      - "rc-*"

permissions:
  contents: write

jobs:
  tagger:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: rc-*
          append_to_pre_release_tag: rc
